
<!--//

function nullOptions(aMenu){

tot=aMenu.options.length;

if (aMenu.options.length>0)

for (i=0;i<tot;i++)

{

aMenu.options[i]=null

}

aMenu.options.length=0;

}

function MySearchF(){

nullOptions(document.F187.MySelect);

URLs=new Array()
titls=new Array()
Kwds=new Array()
URLs[0]="802.1x.htm";
titls[0]="802.1x";
Kwds[0]="BASE OPERATING SYSYTEM, AAA AUTHENTICATION, COMMAND HISTORY,COMMAND INFORMATION, COMMAND MODE, USAGE GUIDELINE, SERVER GROUP, MASTER CONTROLLER, IP ADDRESS, AUTHENTICATION PROFILE, AUTHENTICATION SERVER, CONFIG MODE, VIA CONNECTION PROFILE, AAA PROFILE,802.1x, AUTHENTIVATION, CONFIGURE, EAP TYPES, EAP, PEAP, EAP-GTC, EAP-AK, EAP_FAST, EAP-MD, EAP-POPTP, EAP-SIM,EAP-TLV, EAP-TTLS, LEAP, ";
URLs[1]="802.1x_XPClient_IAS_Config.htm";
titls[1]="802.1x XPClient IAS Config";
Kwds[1]="REMOTE ACCESS,WINDOW OPENS,WIRELESS NETWORK, WIRELESS NETWORK,802.1X RADIUS SERVER, REMOTE ACCESS POLICY, REMOTE ACCESS PERMISSION, LOCAL CERTIFICATE AUTHORITY, GREEN ARROW ICON, IAS, WINDOWS XP WIRELESS CLIENT EXAMPLE CONFIGURATION, RADIUS";
URLs[2]="AAA_Servers.htm";
titls[2]="AAA_Servers";
Kwds[2]="SERVER GROUP,INTERNAL DATABASE, SERVER DERIVATION RULE, AUTHENTICATION REQUEST, GLOBAL NAS IP, ENTER PARAMETER, MATCH FQDN RULE, AAA SERVERS";
URLs[3]="acronyms-and-terms.htm";
titls[3]="acronyms-and-terms";
Kwds[3]="ACCESS POINT, SMART ANTENNA TECHNOLOGY, HOT SPOT, SHORTEST-WAVELENGTH IR BORDER VISIBLE RED,LAYER TWO TUNNELING PROTOCOL,LONGEST-WAVELENGTH IR BORDER RADIO WAVES, ACRONYMS, TERMS";
URLs[4]="Adding_Local_Switches.htm";
titls[4]="Adding Local Switches";
Kwds[4]="ACCESS POINT, SMART ANTENNA TECHNOLOGY, SHORTEST-WAVELENGTH IR BORDER VISIBLE RED, LEGITIMATE WI-FI ACCESS POINT, ADDING LOCAL SWITCHES";
URLs[5]="AP_Config.htm";
titls[5]="AP_Config";
Kwds[5]="REMOTE AP, DHCP SERVER, SSID PROFILE, HIGH-THROUGHPUT SSID PROFILE, ADAPTIVE RADIO MANAGEMENT, AP SYSTEM PROFILE, AP CONFIGURATION";
URLs[6]="ARM.htm";
titls[6]="ARM";
Kwds[6]="ARM PROFILE, VIRTUAL AP, PROFILE MANAGEMENT, AP GROUP, COVERAGE INDEX, AIR MONITOR, LOAD BALANCING FEATURE, LOCAL REGULATORY REQUIREMENT, ARM";
URLs[7]="Base_WLAN_Switch.htm";
titls[7]="Base_WLAN_Switch";
Kwds[7]="IP ADDRESS,CONFIGURED VLAN INTERFACE IP ADDRESS, CONTROLLER, REMOTE MANAGEMENT CONSOLE,BASE WLAN SWITCH, CONFIGURING,USER-CENTRIC NETWORK, DEPLOYMENT, TASKS, CONFIGURATION, ";
URLs[8]="branch_office_controller.htm";
titls[8]="branch office controller";
Kwds[8]="CONFIG ID, RN CONFIGURATION PROFILE, DNS PROXY SERVER, DEFINING REMOTE NODE ADDRESS POOLS, REMOTE NODE ADDRESS POOL, BRANCH OFFICE CONTROLLER";
URLs[9]="Captive_Portal.htm";
titls[9]="Captive Portal";
Kwds[9]="CAPTIVE PORTAL, CAPTIVE PORTAL AUTHENTICATION PROFILE, CAPTIVE PORTAL PAGE, BASE OPERATING SYSTEM ";
URLs[10]="CertRevocation.htm";
titls[10]="CertRevocation";
Kwds[10]="REVOCATION CHECKPOINT, OCSP SIGNER CERTIFICATE, OCSP RESPONDER, CERTIFICATE, CERTIFICATE REVOCATION";
URLs[11]="control_plane.htm";
titls[11]="control_plane";
Kwds[11]="CAMPUS AP WHITELIST, CAMPUS AP, CONTROL PLANE SECURITY, WHITELIST ENTRY, CONTROL PANE";
URLs[12]="CSS.htm";
titls[12]="CSS";
Kwds[12]="LOW-LATENCY CONTENT SECURITY, VIRTUAL BRANCH NETWORKING, VIRTUAL BRANCH NETWORKING, REMOTE ACCESS POINT, CSS";
URLs[13]="Dashboard_Monitoring.htm";
titls[13]="Dashboard_Monitoring";
Kwds[13]="SORT ICON, AIR QUALITY METRIC, GHZ RADIO BAND, FRAME RATE DISTRIBUTION, DASHBOARD MONITORING";
URLs[14]="Defaults.htm";
titls[14]="Defaults";
Kwds[14]="DEFAULT SELF-SIGNED CERTIFICATE, CAPTIVE PORTAL PROFILE, DECRYPT-TUNNEL FORWARDING MODE,CAPTIVE PORTAL AUTHENTICATION, FORWARDING MODE, TKIP COUNTER MEASURE MANAGEMENT, DEFAULTS,";
URLs[15]="DHCP_Option_43.htm";
titls[15]="DHCP_Option_43";
Kwds[15]="ACCESS CONTROL DECISIONS, OPTIONAL INFORMATION, HARDWARE ADDRESS, WIRELESS NETWORK, DHCP, ";
URLs[16]="ESI.htm";
titls[16]="ESI";
Kwds[16]="AVF SERVER DEVICE, SYSLOG MESSAGE, AVF SERVER, ESI PARSER DOMAIN, PARSER RULE TEST, PARSER RULE TEST,WEB-BASED USER INTERFACE, 17-CHARACTER MAC ADDRESS, ESI";
URLs[17]="Firewall_Port_Info.htm";
titls[17]="Firewall_Port_Info";
Kwds[17]="PERMANENT PAPI CONNECTION,REMOTE AP, FIREWALL PORT INFO, FIREWALL, PORT, INFORMATION, PORT INFO";
URLs[18]="Firewall_Roles.htm";
titls[18]="Firewall_Roles";
Kwds[18]="BANDWIDTH CONTRACT, VIRTUAL PRIVATE NETWORKS, PRECONFIGURED INTERNAL BANDWIDTH CONTRACT EXCEPTION LIST, VLAN BANDWIDTH CONTRACT MAC EXCEPTION LIST, ROLES, FIREWALL ROLLS";
URLs[19]="Grenache.htm";
titls[19]="Grenache";
Kwds[19]="SITE-TO-SITE VPN EDGE DEVICE, DIALER GROUP,INTERNAL AP, NOVATEL MODEM MODE-SWITCH, SCSI REZERO COMMAND, SPECIFIC USB COMMAND, GRENACHE";
URLs[20]="Internal_Captive_Portal.htm";
titls[20]="Internal_Captive_Portal";
Kwds[20]="CAPTIVE PORTAL, PAGE TYPE, PAGE TEXT, CAPTIVE PORTAL PAGE, INTERNAL CAPTIVE PORTAL, CAPTIVE PORTAL, PORTAL,";
URLs[21]="IPv6.htm";
titls[21]="IPv6";
Kwds[21]="IPV6 ADDRESS, EXTERNAL IPV6 ROUTER, IPV6 AP, IPV6,";
URLs[22]="LACP.htm";
titls[22]="LACP";
Kwds[22]="PASSIVE STATE, SYSTEM ID/KEY, PORT-CHANNEL INTERFACE WAIT, ACTIVE STATE, STATIC PORT MEMBER, ACTOR SYSTEM ID, LACP,";
URLs[23]="MAC_Authentication.htm";
titls[23]="MAC_Authentication";
Kwds[23]="INTERNAL DATABASE, MAC AUTHENTICATION PROFILE, MAC-BASED AUTHENTICATION, MAC-BASED AUTHENTICATION, AAA_SERVERS, MAC,  ";
URLs[24]="Management_Utilities.htm";
titls[24]="Management_Utilities";
Kwds[24]="CLIENT CERTIFICATE, GUEST PROVISIONING PAGE, PASSWORD POLICY, GUEST PROVISIONING PAGE DISPLAYS, GUEST PROVISIONING PAGE DISPLAYS. SERVER CERTIFICATE, GUEST PROVISIONING PAGE DISPLAYS, MANAGEMENT, MANAGEMENT UTILITIES, UTILITIES";
URLs[25]="Mesh.htm";
titls[25]="Mesh";
Kwds[25]="MESH POINT, MESH, MESH PORTAL, RADIO, PROFILE, MESH NODE, NODE, AP GROUP, RECOVERY PROFILE, MESH LINK, ARM PROFILE, MESH NETWORK, DATE(),";
URLs[26]="Mobility.htm";
titls[26]="Mobility";
Kwds[26]="MOBILITY, HOME AGENT, MOBILITY DOMAIN, MOBILE CLIENT, FOREIGN AGENT, VIRTUAL AP, DATE()";
URLs[27]="Mux_config.htm";
titls[27]="Mux_config";
Kwds[27]="ACTIVE TUNNELED NODE PORT, MUX, MUX CONFIGURATION, CONTROLLER, TRUNK PORT, AP LICENSE USAGE, VLAN SETTING, TUNNELED NODE CLIENT";
URLs[28]="Network_Parameters.htm";
titls[28]="Network Parameters";
Kwds[28]="IP ADDRESS, GRE TUNNEL, VLAN INTERFACE, CONFIGURE VLAN INTERFACE ADDRESS, LOOPBACK INTERFACE ADDRESS, NETWORK PARAMETERS, ACTIVE-STANDBY TOPOLOGY,";
URLs[29]="New_Licenses.htm";
titls[29]="New Licenses";
Kwds[29]="IP ADDRESS, NEW LICENSES, LICENSES, ADD, GRE TUNNEL, VLAN INTERFACE, ACTIVE STANDBY TOPOLOGY, VLAN BANDWIDTH CONTRACT MAC EXCEPTION LIST, LOOPBACK INTERFACE ADDRESS, NEW LICENSES";
URLs[30]="New_WIP.htm";
titls[30]="New_WIP";
Kwds[30]="ROGUE AP, STANDARD SETTING, MAC ADDRESS, NEW WIP, ROGUE AP CLASSIFICATION TECHNIQUES OTHER THAN AP CLASSIFICATION RULES,WIRELESS INTRUSION PREVENTION, HOTSPOT SERVICE PROVIDER, WIP";
URLs[31]="New_WIP_Advanced.htm";
titls[31]="New_WIP_Advanced";
Kwds[31]="5-MHZ GRANULAR CHANNEL SCANNING,RESPONSE FRAME,UNAUTHORIZED WIRELESS DEVICE,ALL-REG-DOMAIN CHANNEL GROUP,DUAL RADIO AP, AP ARM SCAN-TIME, DYNAMIC SCANNING DWELL, CHANNEL DWELL, WIP ADVANCED FEATURES, WIP, WIP ADVANCED"
URLs[32]="OSPF.htm";
titls[32]="OSPF";
Kwds[32]="UPSTREAM ROUTER, GRE TUNNEL, CENTRAL OFFICE, OSPF, BRANCH OFFICE, ROUTER LSA, GRE TUNNEL, USER SUBNET, OSPF CONTROL PACKET, ENABLE OSPF, UPLINK TUNNELS, OPEN SHORTEST PATH FIRST, INTERIOR GATEWAY ROUTING PROTOCOL,OSPF,";
URLs[33]="phonehome.htm";
titls[33]="phonehome";
Kwds[33]="PHONEHOME, SMTP SERVER, PHONEHOME AUTOMATIC REPORTING FEATURE, CONFIGURATION FILE, MAXIMUM EMAIL SIZE, PHONEHOME DATA FILE ATTACHMENT, MAXIMUM EMAIL SIZE, HARDWARE STATUS, PHINEHOME ATTACHMENT, SECURE EMAIL, PHONEHOME STATUS, EMAIL SERVER, SMALL ATTACHEMENT, LOCAL NETWORK,";
URLs[34]="Preface.htm";
titls[34]="Preface";
Kwds[34]="NETWORK PARAMETERS, PREFACE, STANDARD WEB BROWSER, DIAGNOSE WLAN ISSUE,EASY-TO-FOLLOW CONFIGURATION TASK, REMOTW MANAGEMENT CONSOLE, WEBUI DASHBOARD, TELNET SESSION, ANGLE BRACKETS, DASHBOARD MONITORING, CONFIGURATION WIZARD, AUDIENCE, FUNDAMENTALS, RELATED DOCUMENTS, CONVENTIONS, CONTACT, SUPPORT, ";
URLs[35]="ProvisioningRAP-at-Home.htm";
titls[35]="ProvisioningRAP-at-Home";
Kwds[35]="PROVISIONING RAP AT HOME, OPTIONAL PARAMETER, CELLULAR CONNETION, COMMON MODEM, ETHERNET CONNECTION, REMOTE AP";
URLs[36]="PVST+.htm";
titls[36]="PVST+";
Kwds[36]="PVST, PROTOCOLS, NATIVE LAN, ENABLE PVST, PVST+, PER-VLAN SPANNING TREE PLUS,  LOAD BALANCING OF VLANS ACROSS MULTIPLE PORTS";
URLs[37]="Remote_AP.htm";
titls[37]="Remote_AP";
Kwds[37]="REMOTE AP, ACCESS POINT, IP ADDRSS, VIRTUAL AP PROFILE, DHCP SERVER, BANDWIDTH RESERVATION, DHCP SERVER, BANDWIDTH RESERVATION,REMOTE AP DHCP SERVER INTERCEPT,FORWARD MODE SETTING, REMOTE AP MODE, REMOTE AP OPERATION, IPSEC TUNNEL, SSID PROFILE, LMS IP ADDRESS";
URLs[38]="RF_Plan.htm";
titls[38]="RF_Plan";
Kwds[38]="RF PLAN, DIALOG BOX, AP MODELING PARAMETERS PAGE, STATUS BAR, RF PLAN PAGES, NON-PRINTABLE CONTROL CHARACTERS, OPTIMUM LOCATION, AM PLAN PAGE, GHZ, ";
URLs[39]="RSTP.htm";
titls[39]="RSTP";
Kwds[39]="RAPID CONVERGENCE, BRIDGE PROTOCOL DATA UNITS, RX COUNTER, UNTAGGED VLAN, POINT-TO POINT LINK, RAPID SPANNING TREE PROTOCOL, FORWARDING STATE, NEIGHBOR BRIDGE, SPANNING TREE, RSTP";
URLs[40]="Spectrum_Analysis.htm";
titls[40]="Spectrum_Analysis";
Kwds[40]="SPECTRUM ANALYSIS, SPECTRUM MONITOR, HYBRID AP, DROP-DOWN LIST, DUTY CYCLE, ACTIVE DEVICE, OPTION MENU, CONFIGURATION SETTING, SWEPT SPECTOGRAM, MONITORED CHANNEL, SPECTRUM DASHBOARD, OVERRIDE, ";
URLs[41]="stateful_authentication.htm";
titls[41]="stateful_authentication";
Kwds[41]="STATEFUL NTLM AUTHENTICATION, NTLM AUTHENTICATION, RADIUS SERVER, WISPR AAA SERVER, AUTHENTICATION MESSAGE, PARTNER ISP, WIDOW PANE, WISPR, STATEFUL AUTHENTICATION";
URLs[42]="VIA.htm";
titls[42]="VIA";
Kwds[42]="VIA CONNECTION, PROFILE, CONTENT SECURITY SERVICE, POLICY ENFORCEMENT FIREWAL VIRTUAL PRIVATE NETWORK, CONNECTION PROFILE, VIA CLIENT, WEB AUTHENTICATION,VIRTUAL INTRANET ACCESS";
URLs[43]="VIA-EndUserInstructions.htm";
titls[43]="VIA-EndUserInstructions";
Kwds[43]="REMOTE SERVER, ALTERNATE CONNECTION PROFILE, PROXY AUTHENTICATION CREDENTIAL, DIAGNOSTIC TOOL, LOG FILE, UPGRADE REQUIREMENT, VIRTUAL INTRANET ACCESS";
URLs[44]="VirtualAPs.htm";
titls[44]="VirtualAPs";
Kwds[44]="VIRTUAL ACCESS POINT, VAP, SHORT GAURD INTERVAL, DROP-DOWN LIST, GAURD INTERVAL, TUNNEL MODE, AUTHENTICATION SERVER, HEX CHARACTER, MEASUREMENT DURATION TIMER, CURRENT ERROR, SERVER GROUP, 802.1X AUTHENTICATION, SERVER GROUP, SSID PROFILE POP-UP WINDOW, SUITE-B CRYOTIGRAPHY, VIRTUAL APS, VIRTUAL AP, AP,";
URLs[45]="Voice_Video.htm";
titls[45]="Voice_Video";
Kwds[45]="VOICE CLIENT, VOICE VIDEO, TRANSMISSION DURATION, VIRTUAL AP LIST, DIAL PLAN, ACCESS CATEGORY, AP HANDOFF INFORMATION, USER RULES SUMMARY LIST, APPLICABLE VIRTUAL AP PROFILE, VIDEO TRAFFIC, DYNAMIC MULTICAST OPTIMIZATION,";
URLs[46]="VPNS.htm";
titls[46]="VPNS";
Kwds[46]="DROP-DOWN LIST, DROP DOWN, NAT POOL, AUTHENTICATION TYPE, NEGOTIATION REQUEST, NEXT-HIGHEST PRIORITY MAP, CUSTOM IPSEC DYNAMIC MAP INSTEAD, DIFFIE HELLMAN GROUP, USER-LEVEL AUTHENTICATION, PPP FRAME, THIRD-PARTY VPN, DESITNATION NAT, PPP, VIRTUAL PRIVATE NETWORKS, VPNS, VPN";
URLs[47]="VRRP.htm";
titls[47]="VRRP";
Kwds[47]="CONTROLLER, ADMIN STATE, VIRTUAL IP ADDRESS, LMS IP, AP GROUP, VRRP INSTANCE, GLOBAL CONFIGURATION COMMAND, VRRP MASTER, RF PLAN DATUM, REDUNDANCY PARAMETERS, VRRP";
URLs[48]="XML_API.htm";
titls[48]="XML_API";
Kwds[48]="XML REQUEST, XML, XML API, API SERVER, USER ENTRY, AUTHENTICATION COMMAND REQUEST PROCESS, XML RESPONSE, SAMPLE CODE, ACTUAL USER MANAGEMENT TASKS, AUTHENTICATION COMMAND, HTTPS POST, XML REQUEST FORMAT,";
URLs[49]="xSec.htm";
titls[49]="xSec";
Kwds[49]="apply, xsec client, applicable 802.1x authentication profile, applicable, xSec, Layer 2 traffic,XSEC";




/* ..... There are a lot of URLs, Keywords, Titles so I have just included the first set for one page */

var joined=new Array()

/* We start off a new array by joining together the titles and keywords */
var joined=new Array()

{

for (i=0;i<URLs.length; i++){

	joined[i]=titls[i]+Kwds[i]
}
Searchphrase=document.F187.MyText.value
j=0;
checker=0;
if (document.F187.MyText.value.length<1){
	alert('Please enter something to search for.');
}

else {

	var myFoundURL=new Array();
	var myFoundText=new Array();
	for (i=0;i<URLs.length; i++)
	
	{
	
		if (joined[i].indexOf(Searchphrase.toUpperCase())>-1){
		
			checker+=1;
			j++;
			myFoundURL[j]=URLs[i];
			myFoundText[j]=titls[i];
		}
	}

if (checker>0){
	document.F187.MySelect.options[0]=new Option('Results: '+checker,'')
	for (j=1;j<checker+1;j++){
		document.F187.MySelect.options[j]=
new Option(myFoundText[j],myFoundURL[j]);

	}
}
else {
	document.F187.MySelect.options[0]=new Option('Sorry! Couldn\'t find anything:','')

}
}
}

//Older Netscapes like a refresh, but Microsoft doesn't and nor does Net 7
/*if (navigator.appName.indexOf("Netscape")>-1)
history.go(0)*/
}
//-->

<!--//
function searchGo(){
	if (document.F187.MySelect.selectedIndex>0){
		parent.page.location=document.F187.MySelect.options[document.F187.MySelect.selectedIndex].value
	}
	else {
		alert('Please select an option.')
	}
}

//-->

